#
# Makefile for misc devices that really don't fit anywhere else.
#
include $(srctree)/drivers/misc/mediatek/cam_cal/src/Makefile.custom

obj-$(CONFIG_MTK_CAM_CAL_OV8858_OTP_SUPPORT)			+= OV8858_OTP.o
