subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include
subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
#
# Makefile for the input sensor drivers.
#
# Each configuration option enables a list of files.

obj-$(CONFIG_SENSOR_TOUCH_KEY_ATMF04) += atmf04.o